channels:
  - conda-forge
dependencies:
  - pip
  - psutil==5.9.5
  - pip:
    - llnl-thicket[extrap,plotting]==2024.1.0
    - ipython==8.13.0
    - scikit-learn
    - alembic==1.11.3
    - anyio==3.7.1
    - argon2-cffi==23.1.0
    - argon2-cffi-bindings==21.2.0
    - arrow==1.2.3
    - asttokens==2.2.1
    - async-generator==1.10
    - async-lru==2.0.4
    - attrs==23.1.0
    - babel==2.12.1
    - backcall==0.2.0
    - beautifulsoup4==4.12.2
    - bleach==6.0.0
    - certifi==2023.7.22
    - certipy==0.1.3
    - cffi==1.15.1
    - charset-normalizer==3.2.0
    - comm==0.1.4
    - cryptography==41.0.3
    - debugpy==1.6.7.post1
    - decorator==5.1.1
    - defusedxml==0.7.1
    - executing==1.2.0
    - fastjsonschema==2.18.0
    - fqdn==1.5.1
    - greenlet==2.0.2
    - idna==3.4
    - ipykernel==6.25.1
    - isoduration==20.11.0
    - jedi==0.19.0
    - jinja2==3.1.2
    - json5==0.9.14
    - jsonpointer==2.4
    - jsonschema[format-nongpl]==4.19.0
    - jsonschema-specifications==2023.7.1
    - jupyter-client==8.3.0
    - jupyter-core==5.3.1
    - jupyter-events==0.7.0
    - jupyter-lsp==2.2.0
    - jupyter-server==2.7.2
    - jupyter-server-terminals==0.4.4
    - jupyter-telemetry==0.1.0
    - jupyterhub==4.0.2
    - jupyterlab==4.0.5
    - jupyterlab-pygments==0.2.2
    - jupyterlab-server==2.24.0
    - mako==1.2.4
    - markupsafe==2.1.3
    - matplotlib-inline==0.1.6
    - mistune==3.0.1
    - nbclassic==1.0.0
    - nbclient==0.8.0
    - nbconvert==7.7.4
    - nbformat==5.9.2
    - nbgitpuller==1.2.0
    - nest-asyncio==1.5.7
    - notebook-shim==0.2.3
    - oauthlib==3.2.2
    - overrides==7.4.0
    - packaging==23.1
    - pamela==1.1.0
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - platformdirs==3.10.0
    - prometheus-client==0.17.1
    - prompt-toolkit==3.0.39
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pycparser==2.21
    - pygments==2.16.1
    - pyopenssl==23.2.0
    - python-dateutil==2.8.2
    - python-json-logger==2.0.7
    - pyyaml==6.0.1
    - pyzmq==25.1.1
    - referencing==0.30.2
    - requests==2.31.0
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rpds-py==0.9.2
    - ruamel-yaml==0.17.32
    - ruamel-yaml-clib==0.2.7
    - send2trash==1.8.2
    - six==1.16.0
    - sniffio==1.3.0
    - soupsieve==2.4.1
    - sqlalchemy==2.0.20
    - stack-data==0.6.2
    - terminado==0.17.1
    - tinycss2==1.2.1
    - tornado==6.3.3
    - traitlets==5.9.0
    - typing-extensions==4.7.1
    - uri-template==1.3.0
    - urllib3==2.0.4
    - wcwidth==0.2.6
    - webcolors==1.13
    - webencodings==0.5.1
    - websocket-client==1.6.1
    # - ipython==7.15.0
    # - ipython-genutils==0.2.0
    # - psutil==5.9.5
