name: Build containers for the Thicket Tutorial

on:
  workflow_dispatch:
    inputs:
      tutorial_name:
        description: 'Name of the tutorial. Will be used as the container tag.'
        required: true
        type: string

jobs:
  build-containers:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        registry_url_base: ["ghcr.io/LLNL"]
        container_info: [["thicket-tutorial-hub", "docker/Dockerfile.hub"],
                         ["thicket-tutorial-init", "docker/Dockerfile.init"],
                         ["thicket-tutorial-spawn", "docker/Dockerfile.spawn"]]

  steps:
  - name: Clone the thicket-tutorial repo
    uses: actions/checkout@v4

  - name: Clean unneeded stuff in runner to make space for the Docker image
    uses: jlumbroso/free-disk-space@v1.3.1
    with:
      tool-cache: false
      android: true
      dotnet: true
      haskell: true
      large-packages: true
      docker-images: false
      swap-storage: true

  - name: GHCR Login
    uses: docker/login-action@v3
    with:
      registry: ghcr.io
      username: ${{ github.actor }}
      password: ${{ secrets.GITHUB_TOKEN }}
      
  - name: Pull existing layers
    env:
      container: ${{ matrix.registry_url_base }}/${{ matrix.container_info[0] }}:${{ inputs.tutorial_name }}
    run: |
      docker pull ${container} || echo "${container} has not been pushed yet"

  - name: Build Container
    env:
      container: ${{ matrix.registry_url_base }}/${{ matrix.container_info[0] }}:${{ inputs.tutorial_name }}
      dockerfile: ${{ matrix.container_info[1] }}
    run: |
      docker build -f ${dockerfile} -t ${container} .

  - name: Deploy Container
    env:
      container: ${{ matrix.registry_url_base }}/${{ matrix.container_info[0] }}:${{ inputs.tutorial_name }}
    run: docker push ${container}
